### ISSUE TITLE
Fetch error on the https://altzone.netlify.app/clans/all 

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-WebPages#1]
I see the error: 
{"status":"FETCH_ERROR","error":"TypeError: Failed to fetch"} 
in the "kaikki klaanit" table instead of clans' data  
![clan_bug](https://github.com/Alt-Org/Altzone-WebPages/assets/47395053/0d3d0ef9-4f56-4734-bbce-3ef64a4e049c)

**Comment by leolab1337** [comment]
Hello, the issue is related to the server side. We are waiting for the server to obtain a domain name and SSL certificate. Once that's done, the client host will be able to communicate with the API.
