### ISSUE TITLE
Make notice of iPhone webgl issues

### ISSUE THREAD

**Issue by Jonroi** [Alt-Org/Altzone-WebPages#100]
There is some issues that webgl game not working on iphones or Mac computers so need to inform that to users.

Mainpage or somewhere that is noticed before trying to access game?
<img width="338" alt="image" src="https://github.com/user-attachments/assets/2ec574a4-5358-4719-b0d9-1a082219fc4f">

**Comment by leolabdev** [comment]
should be designed in figma first
