### ISSUE TITLE
fix/refactor authUserSlice to not have profile state

### ISSUE THREAD

**Issue by leolabdev** [Alt-Org/Altzone-WebPages#111]
authUserSlice has taken on too many responsibilities, it should be solely responsible for whether the user is logged in

- [ ] create profileSlice
- [ ] profile slice should get profile data after profileApi makes backend request (we should not define it on auth request) 
- [ ] we could make the profile getting and saving actions right after auth request but via profileSlice/profileApi

**Comment by Skoivumaki** [comment]
#246

**Comment by Skoivumaki** [comment]
Closed since #246 completes this.
