### ISSUE TITLE
Fix Clanpage responsive issue

### ISSUE THREAD

**Issue by Jonroi** [Alt-Org/Altzone-WebPages#118]
Content goes over bottom border when mobile are sideways

Phone: Nord 2 (2400 × 1080) 

![Screenshot_2024-09-29-01-29-59-30_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/22c48a65-6cb4-4462-a0a6-3d3f610c801a)

**Comment by leolabdev** [comment]
Known issue because of our navbar, I suggest using min() , or clamp() function. Example : " margin-top: min(10vh, 200px);"

**Comment by Jonroi** [comment]
After the navbar update, the issue has been resolved and could not be reproduced on my device or on others tested.
