### ISSUE TITLE
Fix button freezing issue 

### ISSUE THREAD

**Issue by leolabdev** [Alt-Org/Altzone-WebPages#119]
The following button has couple of animations. That behaviour doesn't work well on some mobile devices. The button freezes in the middle of animation. 

- [ ] Fix the problem
- [ ] Save the animation

![image](https://github.com/user-attachments/assets/4e56f4b7-a551-4526-87e8-43150e455c6c)

**Comment by leolabdev** [comment]
Should we do anything about this component at all or does management no longer want comic advertising on the main page?

**Comment by Jonroi** [comment]
Managment probably wants to advertise but they dont have permission for story to be  "advertised"... so comic needs to be "hidden" but foundable at somewhere like in gallery.

**Comment by Jonroi** [comment]
This is not relevant anymore. i delete this so none uses their time on to find thhat button.
