### ISSUE TITLE
clans page header is not translated 

### ISSUE THREAD

**Issue by leolabdev** [Alt-Org/Altzone-WebPages#124]
![image](https://github.com/user-attachments/assets/28eede8a-ccbb-47f7-ac3f-0593b9031151)

**Comment by Skoivumaki** [comment]
Added requested text translation for clan title and no result text (if nothing was found with search)
Removed old unnecessary debug code.
<img width="566" alt="image" src="https://github.com/user-attachments/assets/0aac9601-21f6-4fb0-a449-c0bcc766fac3">
