### ISSUE TITLE
Team page enhancement 

### ISSUE THREAD

**Issue by Jonroi** [Alt-Org/Altzone-WebPages#131]
# Make logo popup and adjust CSS on team page

- [x] Add functionality to make the logo enlarge on mouse click ("popup"). A second click should remove the enlargement.
- [x] Adjust the task so that it aligns properly with the name.
- [x] Ensure the logo is equidistant when rendered alone.
- [x] Verify that responsiveness is maintained across all devices, both horizontally and vertically.

- [x] Make task section text smaller and without bold for better view (image below)
![image](https://github.com/user-attachments/assets/5da694c7-ee3e-4178-b827-7971473dd30a)

**Comment by leolabdev** [comment]
waiting for #101  to be done

**Comment by Jonroi** [comment]
This have done and merged from jarno/enhancement/131-team-page-enhancement-3
