### ISSUE TITLE
Add join us page

### ISSUE THREAD

**Issue by Jonroi** [Alt-Org/Altzone-WebPages#158]
### Add join us page
---
- [ ] add new join us page "see how other similar pages are done"
- [ ] add routings
- [ ] add navbar paths
- [ ] add comingSoon component for page from our library 
---
<img width="911" alt="image" src="https://github.com/user-attachments/assets/8ef4850f-6f13-4727-960e-ccbb76443f4d">

---

- [ ] make sure it gives right path
- [ ] make sure that link shows and works at mobile and desktop navbar

**Comment by leolabdev** [comment]
Maybe it's better not to add so many of these pages that will be ready soon? At least don't touch the navbar now, or just change the link from discord to duunitori there
