### ISSUE TITLE
Resolve Logo Rendering Issue

### ISSUE THREAD

**Issue by Jonroi** [Alt-Org/Altzone-WebPages#161]
---

### Resolve Logo Rendering Issue

- [ ] **Rendering**
    - Ensure proper handling of logos on the **Team Page**.
    - The page is managed using **Strapi CMS**.
    - Logos should be uploaded and displayed correctly from the Strapi URL.

-  **Consultation**
    - If needed, consult the issue creator for details on relevant **schemas** and **endpoints**.

- [ ] **Thorough Testing**
    - Ensure that logos render correctly in **all screen sizes** 

---

![Logo Rendering Issue](https://github.com/user-attachments/assets/a51efd49-8f73-49b7-81e1-8f5eac04e53b)

---

**Comment by leolabdev** [comment]
The issue occurs only on localhost; for some reason, we are making the request to the frontend itself instead strapi 
![image](https://github.com/user-attachments/assets/9ca0a330-9a34-414d-928c-fd0749662462)
