### ISSUE TITLE
Refactor heroDevelopment page

### ISSUE THREAD

**Issue by Jonroi** [Alt-Org/Altzone-WebPages#192]
## 🛠 **Refactor Description**

Refactor HeroDevelopment page to use comingSoon component rather than make stylings and content on page

---

## 🔍 **Reason for Refactor**

We now have component called ComingSoon for handling this so needs to use it here.

## ✅ **Expected Outcome**

Describe the expected benefits after refactoring:

- Improved **performance** and **readability**
- Simplified logic or **modular** design
- Reduced **complexity** and improved **maintainability**

---

## 📋 **Additional Information**
| ![Image 1]<img width="583" alt="image" src="https://github.com/user-attachments/assets/6e8e0e61-473a-4a6c-ae76-1884301ac4e0"> | ![Image 2](https://github.com/user-attachments/assets/61d36a64-8f21-4821-a5ce-c336068b9fda) |
|:---:|:---:|

**Comment by leolabdev** [comment]
@juho236 @Jonroi By the way, why do we need this page at all?

**Comment by Jonroi** [comment]
It's going to show tons of information how player can upgrade different characters and they don't want to do it on game so it comes to web page.
