### ISSUE TITLE
Enhancement Request: Create a `MultiSelectionDropdown` component within `CustomForm`

### ISSUE THREAD

**Issue by Skoivumaki** [Alt-Org/Altzone-WebPages#256]
## ✨ **Enhancement Description**

Provide a brief description of the enhancement or improvement being suggested:

- **What is it?**: Create a `MultiSelectionDropdown` component within `CustomForm` to enhance form functionality, allowing users to select multiple options from a dropdown list. Will be used for selecting Clan Labels in clan creation/editing and searching.
- **Why improve it?**: This enhancement will streamline forms that require multi-selection inputs, improving the UX by consolidating multiple checkboxes or selection fields into a single, more efficient component.

---

## 🌟 **Benefits of the Enhancement**

Explain how this enhancement will improve the project or user experience:

- **User Experience**: The MultiSelectionDropdown will make forms more intuitive and compact, reducing visual clutter when multiple options are available for selection. It will offer a smoother interaction by enabling users to quickly select or deselect multiple options.
- **Project Impact**: This component will promote code reusability and maintainability by centralizing multi-selection logic in one place, reducing redundant code across forms. It will also improve the project’s scalability, making it easy to integrate similar functionality in other parts of the application.

---

## 🛠️ **Proposed Implementation**

Outline how the enhancement could be implemented, including any technical considerations:

- **Technical Details**: 
- Utilize React to integrate with form handling.
- Accept an array of options (such as enums) and render them as a dropdown with checkboxes for each option.
- Ensure compatibility with `yup` to handle validation requirements for multi-selection. (might only be relevant when testing)

- **Implementation Plan**:
- Define MultiSelectionDropdown in CustomForm, accepting props like options(array of enums), label, defaultSelected, and onSelectChange.
- Render a dropdown menu where each option has a "checkbox", allowing users to select multiple items. (See links for what it should look like)
- The dropdown menu should also have ability to limit the amount of selections, `maxSelections`: 5 etc.
- Test component integration and validation scenarios to ensure a robust implementation.

---

## 📎 **Additional Information**

Include any additional context, examples, or resources that could help in understanding or implementing the enhancement:

- **Links & References**: https://www.syncfusion.com/react-components/react-multiselect-dropdown (Chip mode)

**Comment by leolabdev** [comment]
You can use a third-party library but wrap it with our wrapper (facade pattern)
