### ISSUE TITLE
AttributesPricing level range

### ISSUE THREAD

**Issue by juhaj77** [Alt-Org/Altzone-WebPages#292]
# Level Calculation Method Updated

## **What's Going Wrong?**

- **Issue**: The current system caps the maximum level at 10, but it needs to be . 
  - Allow up to a total level of 24, where the defaultLevel can go up to 14 with a development level of up to 10. This means the final level calculation should ensure the total level doesn't exceed 24.

- The [StatsPricing Document](https://docs.google.com/spreadsheets/d/1jZlsFm2OWSKYXreRRw3ko9IiBBtzwyPQk4HcduuNU-M/edit?gid=0#gid=0) has been updated:
  - The "kehitysleveli" table now includes a tenth row.
  - The `statsPricingData.ts` file requires updating to reflect these changes.

## **Proposed Improvements**

1. **Variable Naming for Clarity**:
   - Use `stat.defaultLevel` instead of `stat.value`.
   - Introduce `developmentLevel` for additional levels.

2. **Level Calculation**:
   - Define the level value as:
     ```ts
     level = defaultLevel + developmentLevel
     ```

3. **Price Updates**:
   - The prices in `statsPricingData` and the spreadsheet represent the *development level prices*. Ensure the data reflects the updated tenth row.

## **Action Items**

- Update the `statsPricingData.ts` file with the new values from the "kehitysleveli" table.
- Refactor the code to use `stat.defaultLevel` and `developmentLevel` for better clarity.
- Verify the level calculation logic aligns with the updated pricing structure.

**Comment by Jonroi** [comment]
this have been done on issue #267
