### ISSUE TITLE
joni/bug/gamesArtsPage-mobile-skaling-problem

### ISSUE THREAD

**Issue by Jonroi** [Alt-Org/Altzone-WebPages#33]
Members Page has skaling problem on small resolutions (see picture)

<img width="419" alt="issue-members-skaling" src="https://github.com/Alt-Org/Altzone-WebPages/assets/142219973/2331aa7f-8558-4184-8ce3-d6805ba15447">

**Comment by leolabdev** [comment]
I think this is normal if there is no problem up to the size of the iPhone 5?
