### ISSUE TITLE
sakari/feature/clan-overview

### ISSUE THREAD

**Issue by Skoivumaki** [Alt-Org/Altzone-WebPages#48]

**Comment by Skoivumaki** [comment]
listing features/fixes so I dont forget:
### Main feature: Clan Overview page
URL: "altzone.fi/clan/{clan id}"
A page to view clan information which includes: name, small information like wealth and all players in clan listed + their roles. 
Example usage: when viewing all clans page and clicking a clan overview page about said clan is shown.

**Features**

- New component: Clan overview desktop/mobile that includes:
- Viewing all players in clan
- Basic information of clan
- Clan name
- List for browsing clans with search funcitonality
- Ability to Join or Leave clans in overview and endpoints related to them
- New custom hooks for handling clan data and hook to retrieve player status/role in clan
- New query: useGetClanByIdWithPlayersQuery

**Features ready to be used but no implemented yet in backend**

- Most of clan information
- Clan Logo
- Preview of clans soulhome

**Fixes**

- "Request to leave a Clan" API url changed in backend.

**Todo**

- Edit mode in overview or as a separate page
- Change background

**Comment by leolabdev** [comment]
can we close this issue already ?

**Comment by Skoivumaki** [comment]
yes
