### ISSUE TITLE
Fix found bugs with hero group label component

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-WebPages#62]
- [x] The label component is cropping on the hero page on some screens
- [x] The label should have a fixed position down the text container

**Comment by leolabdev** [comment]
it should be smaller and on the center ![image](https://github.com/user-attachments/assets/5539c2a0-984f-4d61-9e54-a562de609859)

**Comment by MikhailDeriabin** [comment]
@leolabdev 

I would suggest to refactor this page overall, as well as fix some bugs I have found on different screen sizes including for example:

1. Hero image is vertically squished
2. There is a vertical scrolling bar appears for the box text (not sure if it's intentional), which is not intuitive in my opinion especially on phones
3. Some text comes out of the bg box on small screens as IPhone 5

After this fixes will be done the label will be much easier to place

**Comment by MikhailDeriabin** [comment]
@leolabdev 

I did start to refactor the component already. I guess I should withdraw them in this case.

As I mentioned earlier the component should be refactored first and only then any changes to the label could be done.

**Comment by leolabdev** [comment]
The new variant will take some time, for this time we need some temporary acceptable result. 
Can't we just use position absolute ?

**Comment by MikhailDeriabin** [comment]
@leolabdev 

I can try it a bit, but if it is only a temporary solution I will not use much time with it
