### ISSUE TITLE
fix register page 

### ISSUE THREAD

**Issue by leolabdev** [Alt-Org/Altzone-WebPages#76]
- [x] we should remove fields: name, backpack capacity and unique identifier

- [x] confirming text should be changed to  -> "vakuutan että olen yli 13 vuotias tai minulla on vanhempieni lupa osallistua pelin sosiaaliseen toimintaan"'

- [x] confirming text should be translated 

![image](https://github.com/user-attachments/assets/009e7dd1-e548-42ed-a7da-a4aa3f70ee98)

**Comment by Skoivumaki** [comment]
Age of consent error box was missing locales, added for languages FI and EN
![image](https://github.com/user-attachments/assets/8399ca81-614f-47a9-8bd4-895280432bdd)

**Comment by Skoivumaki** [comment]
API requires backpackCapacity, uniqueIdentifier and name fields to be filled. Used username as uniqueIdentifier and name to post 201.
![image](https://github.com/user-attachments/assets/facf8bd9-d4ce-46f8-845f-d1072b38c336)
